### ISSUE TITLE
Implementing Settlement during Order Processing

### ISSUE THREAD

**Issue by thdefn** [thdefn/twentysix#40]
## 📌 Feature Issue
> Implementing Settlement during Order Processing

## 📝 To-do
- [x] Set up gRPC communication between the Brand Server and the Order Server
- [x] Retrieve and cache brand information from the Brand Server.
- [x] Calculate based on brand information and order details.

## ETC
>
